config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  get 'workshop/shuffle' => 'workshop#shuffle'
  get 'workshop/shuffleafter' => 'workshop#shuffleafter'
  
  get 'home/shuffle' => 'home#shuffle'
  get 'home/confirm' => 'home#confirm'
  get 'home/shuffleafter' => 'home#shuffleafter'
  resources :emplos
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emplo.rb
class Emplo < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :section, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emplos_controller.rb
class EmplosController < ApplicationController
  before_action :set_emplo, only: [:show, :edit, :update, :destroy]

  # GET /emplos
  # GET /emplos.json
  def index
    @seizou = Emplo.where(section: "製造").order(:id)
    @jimu = Emplo.where(section: "事務").order(:id)
  end

  # GET /emplos/1
  # GET /emplos/1.json
  def show
  end

  # GET /emplos/new
  def new
    @emplo = Emplo.new
  end

  # GET /emplos/1/edit
  def edit
  end

  # POST /emplos
  # POST /emplos.json
  def create
    @emplo = Emplo.new(emplo_params)

    respond_to do |format|
      if @emplo.save
        format.html { redirect_to emplos_path, notice: 'Emplo was successfully created.' }
        format.json { render :show, status: :created, location: @emplo }
      else
        format.html { render :new }
        format.json { render json: @emplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emplos/1
  # PATCH/PUT /emplos/1.json
  def update
    respond_to do |format|
      if @emplo.update(emplo_params)
        format.html { redirect_to @emplo, notice: 'Emplo was successfully updated.' }
        format.json { render :show, status: :ok, location: @emplo }
      else
        format.html { render :edit }
        format.json { render json: @emplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emplos/1
  # DELETE /emplos/1.json
  def destroy
    @emplo.destroy
    respond_to do |format|
      format.html { redirect_to emplos_url, notice: 'Emplo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emplo
      @emplo = Emplo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emplo_params
      params.require(:emplo).permit(:name, :section, :last)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @seizou = Emplo.where(section: "製造")
    @jimu = Emplo.where(section: "事務")
  end

  def shuffle
    #paramsチェック
    @button = params[:id]
    #レコード詰
    @shuffle = Emplo.all
    @seizou = Emplo.where(section: "製造")
    @jimu = Emplo.where(section: "事務")
    
    if @button != "Fixed"
      #シャッフルされた1..nの配列を作成
      range1 = (1..group1 = Emplo.where(section: "製造").count.to_i).to_a.shuffle!
      range2 = (1..group2 = Emplo.where(section: "事務").count.to_i).to_a.shuffle!
    else
      #グループ確定時の動作
      @seizou.each do |f|
        f.last = f.next
        f.save
      end

      @jimu.each do |f|
        f.last = f.next
        f.save
      end
      flash[:notice] = "グループが確定しました"
    end

    #製造のグループ分け
    i = 0  
    @seizou.each do |f|
      #再抽選の時はセーブしない
      if @button != "Fixed"
        f.next = (range1[i] % 3)
        f.save
        i += 1
      end
    end
    
    #事務のグループ分け
    i = 0
    @jimu.each do |f|
      #再抽選の時はセーブしない
      if @button != "Fixed"
      f.next = (range2[i] % 3)
      f.save
      i += 1
      end
    end
  end

  def shuffleafter
    @shuffle = Emplo.all
  end
  
end

app/controllers/workshop_controller.rb
class WorkshopController < ApplicationController
  def shuffle
    @button = params[:id]
    @seizou = Emplo.where(section: "製造").order(:id)
    @jimu = Emplo.where(section: "事務")

    if @button != "Fixed"
      range = (1..group2 = Emplo.where(section: "事務").count.to_i).to_a.shuffle!
    else
      @jimu.each do |f|
        f.k_last = f.k_next
        f.save
      end
      flash[:notice] = "グループが確定しました"
    end

    i = 0
    @jimu.each do |f|
      if @button != "Fixed"
      f.k_next = (range[i] % 2)
      f.save
      i += 1
      end
    end

  def shuffleafter
    @shuffle = Emplo.all
  end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emplos_helper.rb
module EmplosHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/workshop_helper.rb
module WorkshopHelper
end

app/views/emplos/_form.html.erb
<div class="form-group mx-5 my-4">
  <div class="form-horizontal" role="form">
      <%= form_with(model: emplo, local: true) do |form| %>
        <% if emplo.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(emplo.errors.count, "error") %> prohibited this emplo from being saved:</h2>

            <ul>
              <% emplo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <div class="field form-group">
        <%= form.label :name, :class => "col-md-4 control-label" %>
        <%= form.text_field :name, class:"form-control col-md-3" %>
      </div>
 
      <div class="col-sm-2">
        <%= form.label :section, 'section', class: 'form-label' %>
      </div>

      <div class="form-group row mb-5">
        <div class="col-sm-3 btn-group" data-toggle="buttons">
          <label class="btn btn-outline-danger" style="width:50%">
            <%= form.radio_button :section, "製造" %>　：製造
          </label>
          <label class="btn btn-outline-danger" style="width:50%">
            <%= form.radio_button :section, "事務" %>　：事務
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit('submit',class: 'btn btn-outline-danger mr-2 col-md-1')  %>
        <%= link_to ' Back ', emplos_path, class: 'btn btn-outline-danger col-md-1' %>
      </div>
      <% end %>
  </div>
</div>

app/views/emplos/edit.html.erb
<h1>Editing Emplo</h1>

<%= render 'form', emplo: @emplo %>

<%= link_to 'Show', @emplo %> |
<%= link_to 'Back', emplos_path %>

app/views/emplos/index.html.erb
<div class="row mx-5 my-4">
  <h5>対象者情報を編集できます</h5>
</div>

<div class="row mx-5 my-4">
  <%= link_to '新規追加', new_emplo_path, class: 'btn btn-outline-danger' %>
</div>

    <div class="row mx-4 mt-5">
    <div class="col-md-5">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>製造</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @seizou.each do |emplo| %>
            <tr>
              <td><%= emplo.name %></td>
              <td><%= emplo.section %></td>
              <td><%= link_to 'Edit', edit_emplo_path(emplo) %></td>
              <td><%= link_to 'Destroy', emplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
           <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-5">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>事務</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @jimu.each do |emplo| %>
            <tr>
              <td><%= emplo.name %></td>
              <td><%= emplo.section %></td>
              <td><%= link_to 'Edit', edit_emplo_path(emplo) %></td>
              <td><%= link_to 'Destroy', emplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/emplos/new.html.erb
<div class="row mx-5 mt-5">
    <h5>新規登録</h5>
</div>

<%= render 'form', emplo: @emplo %>

app/views/emplos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emplo.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @emplo.section %>
</p>

<p>
  <strong>Last:</strong>
  <%= @emplo.last %>
</p>

<%= link_to 'Edit', edit_emplo_path(@emplo) %> |
<%= link_to 'Back', emplos_path %>

app/views/home/shuffle.html copy.erb
<h3>組み合わせ作成</h3>

<%= button_to 'シャッフル開始', {controller: 'home', action: 'shuffle'}, {method: :get }%>
<h5>ランチグループ</h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th>グループ1</th>
      <th>グループ2</th>
      <th>グループ3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% num = 0
        numtr = 1
    while numtr <= @n2 do
    %>
    <tr class="col-ms-2">
      <td><%= @aaa[num] %></td>
      <td><%= @aaa[num + 1] %></td>
      <td><%= @aaa[num + 2] %></td>
    </tr>
    <% 
    numtr += 1
    num += 3
    end %>

    <% num2 = 0
        numtr2 = 1
    while numtr2 <= @m2 do
    %>
    <tr>
      <td><%= @bbb[num2] %></td>
      <td><%= @bbb[num2 + 1] %></td>
      <td><%= @bbb[num2 + 2] %></td>
    </tr>
    <% 
    numtr2 += 1
    num2 += 3
    end %>
  </tbody>
</table>
<br>

app/views/home/shuffle.html.erb
<div class="row mx-5 my-4">
  <h3>ランチシャッフル</h3>
</div>

  <div class="row mx-5 mt-5">
    <% if @button != "Fixed" %>
      <%= button_to 'シャッフル！ »', home_shuffle_path, class: 'btn btn-outline-danger mr-1', method: :get, params:{id: "shuffle"} %>
      <%= button_to 'グループ確定 »', home_shuffle_path, class: 'btn btn-outline-danger mx-1', method: :get, params:{id: "Fixed"} %>
    <% end %>
  </div>

  <div class="row mx-4 mt-5">
    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループA</th>
          </tr>
        </thead>
      
        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.next == 0 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループB</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.next == 1 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループC</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.next == 2 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/home/shuffleafter.html.erb
<div class="row mx-5 my-4">
  <h3>前回のランチ組み合わせ</h3>
</div>

  <div class="row mx-4 mt-5">
    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループA</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.last == 0 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループB</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.last == 1 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループC</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.last == 2 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="jumbotron">

        <div class="row m-5">
        <h1>シャッフルランチアプリ</h1>
        </div>

        <div class="row">
        <a class="btn btn-outline-danger btn-lg mt-5 mx-5" href="/home/shuffle" role="button">ランチシャッフル »</a>
        <a class="btn btn-outline-danger btn-lg mt-5" href="/workshop/shuffle" role="button">研修シャッフル　 »</a>
        </div>
      </div>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
　 <div class="alert alert-info"><%= notice %>
     <button type="button" class="close" data-dismiss="alert">&times;</button>
   </div>
<% elsif alert %>
   <div class="alert alert-danger"><%= alert %>
     <button type="button" class="close" data-dismiss="alert">&times;</button>
   </div>
<% end %>

app/views/layouts/_navibar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#be8f68;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/">シャッフルランチ</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item ">
        <a class="nav-link" href="/">ホーム</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/home/shuffle">ランチシャッフル</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/home/shuffleafter">前回のランチ組み合わせ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/workshop/shuffle">研修シャッフル</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/workshop/shuffleafter">前回の研修組み合わせ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/emplos">従業員データ</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title>ShuffleLanch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <!--<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>-->
  </head>

  <body>
  <div class="container-fluid ">
    <%= render 'layouts/navibar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/workshop/shuffle.html.erb
  <div class="row mx-5 my-4">
    <h3>研修組み合わせ</h3>
  </div>

  <div class="row mx-5 mt-5">
    <% if @button != "Fixed" %>
      <%= button_to 'シャッフル！ »', workshop_shuffle_path, class: 'btn btn-outline-danger mr-1',method: :get, params:{id: "shuffle"} %>
      <%= button_to 'グループ確定 »', workshop_shuffle_path, class: 'btn btn-outline-danger mx-1', method: :get, params:{id: "Fixed"} %>
    <% end %>
  </div>

  <div class="row mx-4 mt-5">
    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループA 8:30 ~ 10:30</th>
          </tr>
        </thead>
      
        <tbody>
          <% @seizou.each do |f| %>
            <tr>
                <td><%= f.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループB 10:30 ~ 12:30</th>
          </tr>
        </thead>

        <tbody>
          <% @jimu.each do |f| %>
            <tr>
              <% if f.k_next == 0 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループC 13:30 ~ 15:30</th>
          </tr>
        </thead>

        <tbody>
          <% @jimu.each do |f| %>
            <tr>
              <% if f.k_next == 1 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/workshop/shuffleafter.html.erb
<div class="row mx-5 my-4">
  <h3>前回のランチ組み合わせ</h3>
</div>

  <div class="row mx-4 mt-5">
    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループA 8:30 ~ 10:30</th>
          </tr>
        </thead>
      
        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.section == "製造" %>
              <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループB 10:30 ~ 12:30</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.k_last == 0 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>グループC 13:30 ~ 15:30</th>
          </tr>
        </thead>

        <tbody>
          <% @shuffle.each do |f| %>
            <tr>
              <% if f.k_last == 1 %>
                <td><%= f.name %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>